"""FinancialMetric ORM model — a structured, extracted financial metric (Phase 3A).

Numbers are stored as deterministic, validated relational data, kept separate from
the RAG chunks (ADR-007: "numbers are computed deterministically, not generated by
the LLM"). Every metric retains `source_chunk_id` + `source_text` for auditability
and future citations. The LLM may *assist* extraction but is never the source of
truth — every value passes deterministic validation before it lands here.

`value` is the NORMALIZED ABSOLUTE magnitude (e.g. "$96.7 billion" → 96700000000);
`unit` records the originally-expressed scale (BILLION/MILLION/PERCENT/…) for
provenance. This phase does NOT compute YoY/QoQ/trends — storage only.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Any

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.models.base import UUIDMixin

if TYPE_CHECKING:
    from app.models.report import Report


class FinancialMetric(UUIDMixin, Base):
    __tablename__ = "financial_metrics"

    report_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("reports.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Traceability: the chunk a metric was read from (SET NULL so re-chunking is safe).
    source_chunk_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("document_chunks.id", ondelete="SET NULL"),
        nullable=True,
    )

    metric_name: Mapped[str] = mapped_column(Text, nullable=False)             # as found in text
    normalized_metric_name: Mapped[str] = mapped_column(String(64), nullable=False)  # canonical
    metric_category: Mapped[str] = mapped_column(String(16), nullable=False)

    value: Mapped[Any] = mapped_column(Numeric, nullable=False)                # normalized absolute
    currency: Mapped[str | None] = mapped_column(String(8), nullable=True)     # ISO-ish, or None
    unit: Mapped[str] = mapped_column(String(16), nullable=False)             # scale: MILLION/PERCENT…

    fiscal_year: Mapped[int | None] = mapped_column(Integer, nullable=True)
    fiscal_quarter: Mapped[int | None] = mapped_column(Integer, nullable=True)

    confidence_score: Mapped[float] = mapped_column(Numeric(4, 3), nullable=False)
    extraction_method: Mapped[str] = mapped_column(String(20), nullable=False)
    source_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Optional provenance / discrepancy flags (e.g. rule-vs-LLM conflict). Not a
    # value source — auditing only.
    extraction_metadata: Mapped[dict[str, Any]] = mapped_column(
        "extraction_metadata", JSONB, nullable=False, default=dict
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    report: Mapped[Report] = relationship(back_populates="metrics")

    __table_args__ = (
        CheckConstraint("confidence_score BETWEEN 0 AND 1", name="ck_financial_metrics_confidence"),
        CheckConstraint(
            "fiscal_quarter IS NULL OR (fiscal_quarter BETWEEN 1 AND 4)",
            name="ck_financial_metrics_quarter",
        ),
        CheckConstraint(
            "metric_category IN ('REVENUE','PROFITABILITY','MARGINS','CASH_FLOW',"
            "'DEBT','CAPEX','GUIDANCE','OTHER')",
            name="ck_financial_metrics_category",
        ),
        CheckConstraint(
            "extraction_method IN ('RULE_BASED','LLM_BASED','HYBRID_VALIDATED')",
            name="ck_financial_metrics_method",
        ),
        Index("ix_financial_metrics_report_id", "report_id"),
        Index("ix_financial_metrics_source_chunk_id", "source_chunk_id"),
        Index("ix_financial_metrics_normalized_name", "report_id", "normalized_metric_name"),
        Index("ix_financial_metrics_category", "metric_category"),
    )

    def __repr__(self) -> str:  # pragma: no cover - debug helper
        return (
            f"<FinancialMetric {self.normalized_metric_name}={self.value} "
            f"{self.unit} report={self.report_id}>"
        )
