"""phase9_memos

Revision ID: df98b16c13c6
Revises: 60ece09504c1
Create Date: 2026-06-11 16:39:18.627869+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df98b16c13c6'
down_revision: str | None = '60ece09504c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_memos',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('benchmark_run_id', sa.UUID(), nullable=True),
    sa.Column('memo_type', sa.Enum('SINGLE_COMPANY', 'BENCHMARK_COMPARISON', name='memo_type_enum', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='memo_status_enum', native_enum=False, length=20), server_default='PENDING', nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("memo_type IN ('SINGLE_COMPANY', 'BENCHMARK_COMPARISON')", name=op.f('ck_investment_memos_ck_investment_memos_type')),
    sa.CheckConstraint("status IN ('PENDING', 'GENERATING', 'COMPLETED', 'FAILED')", name=op.f('ck_investment_memos_ck_investment_memos_status')),
    sa.ForeignKeyConstraint(['benchmark_run_id'], ['benchmark_runs.id'], name=op.f('fk_investment_memos_benchmark_run_id_benchmark_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_investment_memos_company_id_companies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_investment_memos_report_id_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investment_memos'))
    )
    op.create_index('ix_investment_memos_company', 'investment_memos', ['company_id'], unique=False)
    op.create_index('ix_investment_memos_report', 'investment_memos', ['report_id'], unique=False)
    op.create_index('ix_investment_memos_status', 'investment_memos', ['status'], unique=False)
    op.create_table('memo_sections',
    sa.Column('memo_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(length=128), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['memo_id'], ['investment_memos.id'], name=op.f('fk_memo_sections_memo_id_investment_memos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memo_sections'))
    )
    op.create_index('ix_memo_sections_memo', 'memo_sections', ['memo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_memo_sections_memo', table_name='memo_sections')
    op.drop_table('memo_sections')
    op.drop_index('ix_investment_memos_status', table_name='investment_memos')
    op.drop_index('ix_investment_memos_report', table_name='investment_memos')
    op.drop_index('ix_investment_memos_company', table_name='investment_memos')
    op.drop_table('investment_memos')
    # ### end Alembic commands ###
